### ISSUE TITLE
"Connect using credentials" wont let me delete typos in username or password

### ISSUE THREAD

**Issue by KainerW** [Bitcoin-Brainbow/Brainbow#106]
I am on a GrapheneOS Pixel 6a.

On the start screen when typing in Salt/Email/Username -> try to type a few letters of your name, stop, make a break of 3-5 seconds, then try to delete one typo you may have made. 

Not possible. Same is valid for the Passphrase field. 

It will let me delete the few newest letters/number (when I made a break in typing the username) but stops at the 5/6 letter and from that on I can not delete letters/numbers anymore.

Bug was present in the version before, I installed newest version and still this bug exists.

**Comment by KainerW** [comment]
Just found out it is the fault of "Simple Keyboard" which is installed on this phone. With the usual keyboard used the bug does not appear.

**Comment by xavierfiechter** [comment]
Thanks for letting me know @KainerW.  

Is this "Simple Keyboard" part of the GrapheneOS package/distribution or an additional app?

**Comment by KainerW** [comment]
an additional app from fdroid

**Comment by xavierfiechter** [comment]
Okay, so let me close this issue here. I suggest opening an issue on the "Simple Keyboard" tracker.
