### ISSUE TITLE
headline_text not working in Toolbar 

### ISSUE THREAD

**Issue by xavierfiechter** [Bitcoin-Brainbow/Brainbow#16]
+        type_height: "large"
+        headline_text: "Headline"

**Comment by 5KRC1** [comment]
headline requires, besides type_height either "large" or "medium", app.material_style == "M3" (docs -> https://github.com/kivymd/KivyMD/blob/master/kivymd/uix/toolbar/toolbar.kv#L111), therefore, you must specify in build function "self.theme_cls.material_style = 'M3'". but it will break some screen layouts.
