### ISSUE TITLE
nowallet keys.py SHA256 && nowallet import | android

### ISSUE THREAD

**Issue by 5KRC1** [Bitcoin-Brainbow/Brainbow#38]
### keys.py > SHA256
While working on [issue #3](https://github.com/Bitcoin-Brainbow/Brainbow/issues/3) I've encountered an error.
Here are the logs:
```
10-09 13:58:03.152	28148	28390	org.brainbow.brainbow	I	python	 Traceback (most recent call last):
10-09 13:58:03.152	28148	28390	org.brainbow.brainbow	I	python	   File "/tmp/tmp5ifac5cw/main.py", line 49, in <module>
10-09 13:58:03.153	28148	28390	org.brainbow.brainbow	I	python	   File "~/Projects/Python/Kivy/Brainbow/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/brainbow/arm64-v8a/nowallet/__init__.py", line 5, in <module>
10-09 13:58:03.153	28148	28390	org.brainbow.brainbow	I	python	   File "~/Projects/Python/Kivy/Brainbow/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/brainbow/arm64-v8a/nowallet/keys.py", line 4, in <module>
10-09 13:58:03.154	28148	28390	org.brainbow.brainbow	I	python	   File "~/Projects/Python/Kivy/Brainbow/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/brainbow/arm64-v8a/Crypto/Hash/SHA256.py", line 23, in <module>
10-09 13:58:03.154	28148	28390	org.brainbow.brainbow	I	python	   File "~/Projects/Python/Kivy/Brainbow/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/brainbow/arm64-v8a/Crypto/Util/_raw_api.py", line 203, in <module>
10-09 13:58:03.155	28148	28390	org.brainbow.brainbow	I	python	   File "~/Projects/Python/Kivy/Brainbow/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/ctypes/__init__.py", line 387, in __getattr__
10-09 13:58:03.156	28148	28390	org.brainbow.brainbow	I	python	   File "~/Projects/Python/Kivy/Brainbow/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/other_builds/python3/arm64-v8a__ndk_target_21/python3/Lib/ctypes/__init__.py", line 392, in __getitem__
10-09 13:58:03.156	28148	28390	org.brainbow.brainbow	I	python	 AttributeError: undefined symbol: PyObject_GetBuffer
```
It says the issue is in nowallet/keys.py in SHA256 import, which uses ctypes. After reading about it online, I've found out ctypes might not yet be supported on python for android. Would it be possible to use another module for SHA256 encryption?

### import nowallet
Other issue is importing nowallet into buildozer. It does not want to use the module from local dir directly, therefore, I've imported brainbow project from github. Then the issue becomes setup.py. It says brainbow not found. The fix is renaming the project to "nowallet" in setup.py [here](https://github.com/Bitcoin-Brainbow/Brainbow/blob/master/setup.py#L2).

**Comment by xavierfiechter** [comment]
The apk is building now automatically using GitHub Actions.

Had to add some custom recipes and made a PR to python-for-android. 

Build process here; https://github.com/Bitcoin-Brainbow/Brainbow/actions after push.

Generated apks can be found here: https://github.com/Bitcoin-Brainbow/Brainbow/tree/data/bin 

Check for commit to pick the correct apk from the list.

![Screenshot 2022-10-19 at 17 11 01](https://user-images.githubusercontent.com/31884704/196731537-c13c8d62-d694-475d-b4fe-5aecf66f532d.png)

import nowallet is fixed. changed the structure of the project.
